### ISSUE TITLE
Unresolved variable in Pending_Defer

### ISSUE THREAD

**Issue by rbw** [nano-wallet-company/nano-wallet-server#1]
There's an unresolved reference to `message` here:
https://github.com/nano-wallet-company/nano-wallet-server/blob/fc0286aec82103a5d4c74700e1dbb42f96b50cc5/nanocast.py#L121

This will cause the error logging to fail.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
