### ISSUE TITLE
No sanity checking in "address decode"

### ISSUE THREAD

**Issue by rbw** [nano-wallet-company/nano-wallet-server#3]
I haven't verified this--but by the looks of it, you can pass an invalid "link" to `RPC_Request` in `Process_Defer`:

https://github.com/nano-wallet-company/nano-wallet-server/blob/fc0286aec82103a5d4c74700e1dbb42f96b50cc5/nanocast.py#L169-L175

Shouldn't it fail with an error if the address isn't of an expected format?

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
