### ISSUE TITLE
Unresolved attribute reference in SendPrices error handling

### ISSUE THREAD

**Issue by rbw** [nano-wallet-company/nano-wallet-server#5]
`handler` doesn't exist in SendPrices(), accessing `handler.request` would raise an (uncaught) exception and logging would fail.

https://github.com/nano-wallet-company/nano-wallet-server/blob/fc0286aec82103a5d4c74700e1dbb42f96b50cc5/nanocast.py#L90

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
