### ISSUE TITLE
limit websocket max message size

### ISSUE THREAD

**Issue by goophile** [nano-wallet-company/nano-wallet-server#8]
According to the tornado documentation, by default, the tornado `WebSocketHandler` limits each WebSocket message at most 10MB.

The `nanocast.py` server used the default value, that's a weakness to potential Deny of Service attack.

I suggest to limit the size (for example 10K)

```py
application = tornado.web.Application([
    (r"/", WSHandler),
], websocket_max_message_size=10240)
```

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
